### PR TITLE
Create modified command listener on uno

### PR DESCRIPTION
**Pull request by Lastrellik**
This is SOOOOOO much easier since I no longer have to deal with SHA1 or string BS or any other convoluted C++ madness.

This pull request contains the code from my previous pull request plus code that allows the Uno to respond to commands from the Raspberry PI. Right now the Raspberry PI code is set up to start the Arduino and then arm it after a few seconds and then disarm it. This is done by sending a single byte through the Serial Port to be deciphered by the Arduino's CommandListener.

### CODE REVIEW

**Comment by Zeustopher** [comment]
I updated this pull request to not show the previous Pull Request's changes as well. _(It was hard to sort through them and know what I've already looked at)_

**Comment by Zeustopher** [comment]
@Lastrellik - I was under the impression based on Wednesday night's discussion that the same 'scheme' would be employed both on the PI side and Arduino side. Ithought the Arduino would be accepting the same 5-digit integer that it would be sending to the PI. So I would have expected a code something similar to `30001` to be passed into the Arduino where `3` represented a Command type message, `0` was NA for logging level, and if `001` was defined as being the Arm command.

**Comment by Lastrellik** [comment]
@zeustopher that shouldn't be too hard. I mostly just need a table for what the three digits numbers mean. Did we have someone working on that? Or was it supposed to be me?

**Comment by Zeustopher** [comment]
@Lastrellik - I know @Boomstick105 was going to be working on replacing the logging but I don't know that we assigned it out to anyone to do the commands. I'm in that file right now documenting a "Code Comment Convention" with these messages so I'll quickly define codes for your commands you have right now (arm, disarm, etc.). I'll get that pushed up in a few minutes and you can make the modifications to this PR to have the Arduino recognize them.

**Comment by Lastrellik** [comment]
@zeustopher have you ran the Java side of things? You should be able to just plug the arduino in and run the Java code from Eclipse and it should automatically select the arduino and run it. I haven't tested it in Linux though.

**Comment by Zeustopher** [comment]
@Lastrellik - PR https://github.com/Lastrellik/Calico-Home-Security/pull/49 is ready with the codes documented.

I haven't yet though I will this afternoon once I get back to working on it.

**Comment by Lastrellik** [comment]
@Zeustopher Can you take a look at it now and tell me what you think?

**Comment by Zeustopher** [comment]
@Lastrellik - Please update the table with those two additional commands for `Execute Command: Trigger` and `Execute Command: ResetCalibration`.

**Pull request merged**
